<html>
	<head>
		<title>Example 6 : A Basic User Login</title>
		<style>
		.showmsg {
			padding: 4px;
			height: 40px;
			background-color: #F2EDC4;
		}
		.hidemsg {
			padding: 0px;
			height: 0px;
			background-color: #FFFFFF;
		}
		</style>
	</head>
	<body>
		<script type="text/javascript" src="/js/ext-4.0.7-gpl/ext-debug.js"></script>
        <link rel="stylesheet" type="text/css" href="/js/ext-4.0.7-gpl/resources/css/ext-all.css">
        <link rel="stylesheet" type="text/css" href="/css/default.css">

        <!-- launch our application -->
        <script type="text/javascript" src="/js/examples/example6/app.js"></script>
	</body>
</html>