<html>
	<head>
		<title>Example 3 : Using Widgets</title>
	</head>
	<body>
		<script type="text/javascript" src="/js/ext-4.0.7-gpl/ext-debug.js"></script>
        <link rel="stylesheet" type="text/css" href="/js/ext-4.0.7-gpl/resources/css/ext-all.css">
        <link rel="stylesheet" type="text/css" href="/css/default.css">

        <!-- launch our application -->
        <script type="text/javascript" src="/js/examples/example3/app.js"></script>
	</body>
</html>