
<?php
header('Location: http://dpcapp.localhost/js/examples/example9/app-test/runner.html');
?>
<!--
<html>
	<head>
		<title>Example 7 : Unit Testing with Jasmine</title>
	</head>
	<body>
		<script type="text/javascript" src="/js/ext-4.0.7-gpl/ext-debug.js"></script>
        <link rel="stylesheet" type="text/css" href="/js/ext-4.0.7-gpl/resources/css/ext-all.css">
        <link rel="stylesheet" type="text/css" href="/css/default.css">

        <script type="text/javascript" src="/js/examples/example7/app.js"></script>
	</body>
</html>
-->