<style>
	body { background-color: #FCB000; margin: 0px; }
	div { font-family: verdana; }
	#content {

	}
	a {
		font-size: 14px;
		text-decoration: none;
		font-weight: bold;
		color: #AE0E0D;
	}
	ul { margin: 0px; padding: 0 0 0 10; }
	li { padding: 3px; }
	div.summary {
		color: #272727;
		font-size: 12px;
		padding-left: 10px;
	}
	h2 { color: #FFFFFF; background-color: #272727; padding: 4px; margin-bottom: 0px; }
	#repo {
		padding-left: 10px;
		padding-top: 8px;
		font-size: 12px;
	}
</style>
<div>
	<h2>&nbsp;ExtJS + Zend Framework</h2>
	<div id="repo">
		<b>source:</b> <a href="https://github.com/enygma/Agile-ExtJS-ZF">https://github.com/enygma/Agile-ExtJS-ZF</a>
	</div><br/>
	<ul>
		<li>
			<a href="/example/example1">1. Setting up a basic application</a>
			<div class="summary">See how to take your first steps into an MVC-based application with Ext JS</div>
		</li>
		<li>
			<a href="/example/example2">2. Setting up a model and store</a>
			<div class="summary">Introducing your first data sources to your application</div>
		</li>
		<li>
			<a href="/example/example3">3. Some Widget Love</a>
			<div class="summary">Examples of a few different "in the box" widgets</div>
		</li>
		<li>
			<a href="/example/example4">4. Working with Layouts</a>
			<div class="summary">Examples of the different kinds of layouts</div>
		</li>
		<li>
			<a href="/example/example5">5. Add/Edit/Remove from a Grid</a>
			<div class="summary">A simple grid that interacts with the database</div>
		</li>
		<li>
			<a href="/example/example6">6. User Authentication with Zend_Auth</a>
			<div class="summary">Creating a user login form that authenticates against a database</div>
		</li>
		<li>
			<a href="/example/example7">7. Unit Testing with Jasmine</a>
			<div class="summary">Simple unit testing using the Jasmne BDD tool</div>
		</li>
		<li>
			<a href="/example/example8">8. Advanced App - Real-time Chat</a>
			<div class="summary">A full application example combining multiple parts</div>
		</li>
	</ul>
</div>